In [1]:
#First import the specific variables needed for the task
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
#Importing the excel files into the database
df1= pd.read_excel(r"C:\Users\Leon's Laptop\Documents\Cowen\Client_Margin_Report_WithClass_TaskDay1.xlsx")
df2= pd.read_excel(r"C:\Users\Leon's Laptop\Documents\Cowen\Client_Margin_Report_WithClass_TaskDay2.xlsx")

In [4]:
#Formatting the columns to the specific types in order to make the data clearer. As well as this, changing to 4 decimal places for accuracy
df1['Quantity']= df1['Quantity'].astype('int64')
df1['Value \n(Local)']= df1['Value \n(Local)'].astype('int64')
df1['Exposure \n(Local)']= df1['Exposure \n(Local)'].astype('int64')
df1['Exposure \n(USD)']= df1['Exposure \n(USD)'].astype('int64')
df1['Exposure \n(Local)']= df1['Exposure \n(Local)'].astype('int64')

df2['Quantity']= df1['Quantity'].astype('int64')
df2['Value \n(Local)']= df1['Value \n(Local)'].astype('int64')
df2['Exposure \n(Local)']= df1['Exposure \n(Local)'].astype('int64')
df2['Exposure \n(USD)']= df1['Exposure \n(USD)'].astype('int64')
df2['Exposure \n(Local)']= df1['Exposure \n(Local)'].astype('int64')
    
pd.set_option('display.float_format', '{:.4f}'.format)

In [5]:
df1.head()

,Instrument,Code,Position Type,Quantity,Unit Price\n(Local)\n,Value \n(Local),Exposure \n(Local),Price Ccy,FX Rate,Instrument Class,Exposure \n(USD),Requirement \n(USD),%Req
0,CT PPTY TR ORD,CTPT LN,Cash,2556887,0.7300,1866527,1866527,GBP,1.2352,Equity,2847796,2242554.4718,78.7470
1,FERGUSON ORD,FERG LN,Cash,1157,113.4500,131261,131261,GBP,1.2352,Equity,200268,43330.1308,21.6360
2,HARBOURVEST GLOBAL ORD,HVPE LN,Cash,131249,22.1000,2900602,2900602,GBP,1.2352,Equity,4425505,1449908.6601,32.7626
3,MAGELLAN GLOBAL UNT,MGF AU,Cash,500000,1.3950,697500,697500,AUD,0.7060,Equity,347659,75219.6294,21.6360
4,NB GLOBAL MONTHLY INCOME FUND ORD,NBMI LN,Cash,3000000,0.7460,2238000,2238000,GBP,1.2352,Equity,3414559,2855789.4108,83.6357

In [6]:
df2.head()

,Instrument,Code,Position Type,Quantity,Unit Price\n(Local)\n,Value \n(Local),Exposure \n(Local),Price Ccy,FX Rate,Instrument Class,Exposure \n(USD),Requirement \n(USD),%Req
0,CT PPTY TR ORD,CTPT LN,Cash,2556887,0.7100,1866527,1866527,GBP,1.2320,Equity,2847796,2169284.1367,78.7273
1,FERGUSON ORD,FERG LN,Cash,1157,113.6000,131261,131261,GBP,1.2320,Equity,200268,43020.3799,21.5646
2,HARBOURVEST GLOBAL ORD,HVPE LN,Cash,131249,22.1000,2900602,2900602,GBP,1.2320,Equity,4425505,1411042.0708,32.0502
3,MAGELLAN GLOBAL UNT,MGF AU,Cash,500000,1.3900,697500,697500,AUD,0.7055,Equity,347659,74596.7618,21.5646
4,NB GLOBAL MONTHLY INCOME FUND ORD,NBMI LN,Cash,3000000,0.7320,2238000,2238000,GBP,1.2320,Equity,3414559,2887549.2833,86.6315

In [7]:
#In order to create a side by side comparison, we merge both the tables together using the common key 'Instrument'
merged_df= pd.merge(df1, df2, on='Instrument')
merged_df.head()

,Instrument,Code_x,Position Type_x,Quantity_x,Unit Price\n(Local)\n_x,Value \n(Local)_x,Exposure \n(Local)_x,Price Ccy_x,FX Rate_x,Instrument Class_x,Exposure \n(USD)_x,Requirement \n(USD)_x,%Req_x,Code_y,Position Type_y,Quantity_y,Unit Price\n(Local)\n_y,Value \n(Local)_y,Exposure \n(Local)_y,Price Ccy_y,FX Rate_y,Instrument Class_y,Exposure \n(USD)_y,Requirement \n(USD)_y,%Req_y
0,CT PPTY TR ORD,CTPT LN,Cash,2556887,0.7300,1866527,1866527,GBP,1.2352,Equity,2847796,2242554.4718,78.7470,CTPT LN,Cash,2556887,0.7100,1866527,1866527,GBP,1.2320,Equity,2847796,2169284.1367,78.7273
1,FERGUSON ORD,FERG LN,Cash,1157,113.4500,131261,131261,GBP,1.2352,Equity,200268,43330.1308,21.6360,FERG LN,Cash,1157,113.6000,131261,131261,GBP,1.2320,Equity,200268,43020.3799,21.5646
2,HARBOURVEST GLOBAL ORD,HVPE LN,Cash,131249,22.1000,2900602,2900602,GBP,1.2352,Equity,4425505,1449908.6601,32.7626,HVPE LN,Cash,131249,22.1000,2900602,2900602,GBP,1.2320,Equity,4425505,1411042.0708,32.0502
3,MAGELLAN GLOBAL UNT,MGF AU,Cash,500000,1.3950,697500,697500,AUD,0.7060,Equity,347659,75219.6294,21.6360,MGF AU,Cash,500000,1.3900,697500,697500,AUD,0.7055,Equity,347659,74596.7618,21.5646
4,NB GLOBAL MONTHLY INCOME FUND ORD,NBMI LN,Cash,3000000,0.7460,2238000,2238000,GBP,1.2352,Equity,3414559,2855789.4108,83.6357,NBMI LN,Cash,3000000,0.7320,2238000,2238000,GBP,1.2320,Equity,3414559,2887549.2833,86.6315

In [8]:
#In order to show the changes in the specified columns, we use subtract dataframe 2 from dataframe 1 in order to show the changes. We also create new columns with the new headers
merged_df['Quantity change'] = merged_df['Quantity_x'] - merged_df['Quantity_y']
merged_df['Price Change'] = merged_df['Unit Price\n(Local)\n_x'] - merged_df['Unit Price\n(Local)\n_y']
merged_df['Local Value Change'] = merged_df['Value \n(Local)_x'] - merged_df['Value \n(Local)_y']
merged_df['Local Exposure Change'] = merged_df['Exposure \n(Local)_x'] - merged_df['Exposure \n(Local)_y']
merged_df['USD Value Change'] = merged_df['FX Rate_x'] - merged_df['FX Rate_y']
merged_df['Requirement Change'] = merged_df['Requirement \n(USD)_x'] - merged_df['Requirement \n(USD)_y']
merged_df['%Req Change'] = merged_df['%Req_x'] - merged_df['%Req_y']

merged_df

,Instrument,Code_x,Position Type_x,Quantity_x,Unit Price\n(Local)\n_x,Value \n(Local)_x,Exposure \n(Local)_x,Price Ccy_x,FX Rate_x,Instrument Class_x,Exposure \n(USD)_x,Requirement \n(USD)_x,%Req_x,Code_y,Position Type_y,Quantity_y,Unit Price\n(Local)\n_y,Value \n(Local)_y,Exposure \n(Local)_y,Price Ccy_y,FX Rate_y,Instrument Class_y,Exposure \n(USD)_y,Requirement \n(USD)_y,%Req_y,Quantity change,Price Change,Local Value Change,Local Exposure Change,USD Value Change,Requirement Change,%Req Change
0,CT PPTY TR ORD,CTPT LN,Cash,2556887,0.7300,1866527,1866527,GBP,1.2352,Equity,2847796,2242554.4718,78.7470,CTPT LN,Cash,2556887,0.7100,1866527,1866527,GBP,1.2320,Equity,2847796,2169284.1367,78.7273,0,0.0200,0,0,0.0032,73270.3352,0.0197
1,FERGUSON ORD,FERG LN,Cash,1157,113.4500,131261,131261,GBP,1.2352,Equity,200268,43330.1308,21.6360,FERG LN,Cash,1157,113.6000,131261,131261,GBP,1.2320,Equity,200268,43020.3799,21.5646,0,-0.1500,0,0,0.0032,309.7510,0.0714
2,HARBOURVEST GLOBAL ORD,HVPE LN,Cash,131249,22.1000,2900602,2900602,GBP,1.2352,Equity,4425505,1449908.6601,32.7626,HVPE LN,Cash,131249,22.1000,2900602,2900602,GBP,1.2320,Equity,4425505,1411042.0708,32.0502,0,0.0000,0,0,0.0032,38866.5892,0.7124
3,MAGELLAN GLOBAL UNT,MGF AU,Cash,500000,1.3950,697500,697500,AUD,0.7060,Equity,347659,75219.6294,21.6360,MGF AU,Cash,500000,1.3900,697500,697500,AUD,0.7055,Equity,347659,74596.7618,21.5646,0,0.0050,0,0,0.0005,622.8675,0.0714
4,NB GLOBAL MONTHLY INCOME FUND ORD,NBMI LN,Cash,3000000,0.7460,2238000,2238000,GBP,1.2352,Equity,3414559,2855789.4108,83.6357,NBMI LN,Cash,3000000,0.7320,2238000,2238000,GBP,1.2320,Equity,3414559,2887549.2833,86.6315,0,0.0140,0,0,0.0032,-31759.8725,-2.9958
5,NEW ENERGY SOLAR STAPLED UNT,NEW AU,Cash,7684727,0.2000,1536945,1536945,AUD,0.7060,Equity,766068,656356.2520,85.6785,NEW AU,Cash,7684727,0.0680,1536945,1536945,AUD,0.7055,Equity,766068,222741.5845,85.6387,0,0.1320,0,0,0.0005,433614.6675,0.0398
6,PANTHEON INTERNATIONAL CF,PIN LN,Cash,1421921,2.6450,3760981,3760981,GBP,1.2352,Equity,5738200,2809681.7488,48.9645,PIN LN,Cash,1421921,2.6450,3760981,3760981,GBP,1.2320,Equity,5738200,2705224.2858,47.3893,0,0.0000,0,0,0.0032,104457.4631,1.5752
7,RESTAURANT BRANDS INTERN,QSR,Cash,-8500,66.5900,-566015,-566015,USD,1.0000,Equity,-566015,84902.2500,15.0000,QSR,Cash,-8500,66.9300,-566015,-566015,USD,1.0000,Equity,-566015,85335.7500,15.0000,0,-0.3400,0,0,0.0000,-433.5000,0.0000
8,THIRD POINT INVESTORS ORD,TPOU LN,Cash,119714,20.4000,2442165,2442165,USD,1.0000,Equity,2442165,1704081.4860,69.7775,TPOU LN,Cash,119714,20.4000,2442165,2442165,USD,1.0000,Equity,2442165,1751012.4531,71.6992,0,0.0000,0,0,0.0000,-46930.9671,-1.9217
9,TRIAN INVESTORS 1 ORD,TI1 LN,Cash,1333000,1.8400,2452720,2452720,GBP,1.2352,Equity,3742161,3706764.6515,99.0541,TI1 LN,Cash,1333000,1.8450,2452720,2452720,GBP,1.2320,Equity,3742161,3710261.6271,99.3932,0,-0.0050,0,0,0.0032,-3496.9756,-0.3391
10,UMG ORD,UMG NA,Synthetic,-44000,23.6350,-49500,-1039940,EUR,1.0851,Equity,-1224469,183670.3566,15.0000,UMG NA,Synthetic,-44000,23.4700,-49500,-1039940,EUR,1.0863,Equity,-1224469,182791.7473,15.0000,0,0.1650,0,0,-0.0012,878.6093,0.0000
11,VPC SPECIALTY LENDING INVESTS ORD,VSL LN,Cash,1070295,0.8380,896907,896907,GBP,1.2352,Equity,1368428,907793.9185,66.3384,VSL LN,Fully Paid,838314,0.8340,4979585,4979585,GBP,1.2320,Equity,7597447,8436085.3051,100.0000,231981,0.0040,-4082678,-4082678,0.0032,-7528291.3867,-33.6616
12,VPC SPECIALTY LENDING INVESTS ORD,VSL LN,Fully Paid,6664284,0.8380,5584669,5584669,GBP,1.2352,Equity,8520637,8520637.3389,100.0000,VSL LN,Fully Paid,838314,0.8340,4979585,4979585,GBP,1.2320,Equity,7597447,8436085.3051,100.0000,5825970,0.0040,605084,605084,0.0032,84552.0338,0.0000
13,AFRICA OPPORTUNITY ORD,AOF LN,Fully Paid,2760062,0.5400,1490433,1490433,USD,1.0000,Equity,1490433,1490433.4800,100.0000,AOF LN,Fully Paid,1070295,0.5400,896907,896907,USD,1.0000,Equity,1368428,1490433.4800,100.0000,1689767,0.0000,593526,593526,0.0000,0.0000,0.0000
14,ALLIED MINDS ORD,ALM LN,Fully Paid,18462237,0.1385,2557019,2557019,GBP,1.2352,Equity,3901293,3901293.8319,100.0000,ALM LN,Fully Paid,2760062,0.1385,1490433,1490433,GBP,1.2320,Equity,1490433,3881106.0581,100.0000,15702175,0.0000,1066586,1066586,0.0032,20187.7738,0.0000
15,AMEDEO AIR FOUR PLUS ORD,AA4 LN,Fully Paid,23788430,0.4000,9515372,9515372,GBP,1.2352,Equity,14517784,14517784.2331,100.0000,AA4 LN,Fully Paid,18462237,0.4000,2557019,2557019,GBP,1.2320,Equity,3901293,14442659.9905,100.0000,5326193,0.0000,6958353,6958353,0.0032,75124.2426,0.0000
16,ASEANA PROPERTIES ORD,ASPL LN,Fully Paid,8000000,0.1400,1120000,1120000,USD,1.0000,Equity,1120000,1120000.0000,100.0000,ASPL LN,Fully Paid,23788430,0.1400,9515372,9515372,USD,1.0000,Equity,14517784,1120000.0000,100.0000,-15788430,0.0000,-8395372,-8395372,0.0000,0.0000,0.0000
17,DORIC NIMROD AIR TWO LTD,DNA2 LN,Fully Paid,4242783,1.0350,4391280,4391280,GBP,1.2352,Equity,6699860,6699860.1239,100.0000,DNA2 LN,Fully Paid,8000000,1.0400,1120000,1120000,GBP,1.2320,Equity,1120000,6697389.7788,100.0000,-3757217,-0.0050,3271280,3271280,0.0032,2470.3451,0.0000
18,ENERGYO SOLUTIONS INVEST ORD,EOS SF,Fully Paid,909529,0.0000,0,0,SEK,0.0962,Equity,0,0.0000,0.0000,EOS SF,Fully Paid,4242783,0.0000,4391280,4391280,SEK,0.0956,Equity,6699860,0.0000,0.0000,-3333254,0.0000,-4391280,-4391280,0.0006,0.0000,0.0000
19,JPEL PRIVATE EQUITY ORD,JPEL LN,Fully Paid,445179,1.1400,507504,507504,USD,1.0000,Equity,507504,507504.0600,100.0000,JPEL LN,Fully Paid,909529,1.1400,0,0,USD,1.0000,Equity,0,507504.0600,100.0000,-464350,0.0000,507504,507504,0.0000,0.0000,0.0000
20,KUBERA CROSS-BORDER FUND,KUBC LN,Fully Paid,4518981,0.0500,225949,225949,USD,1.0000,Equity,225949,225949.0500,100.0000,KUBC LN,Fully Paid,445179,0.0500,507504,507504,USD,1.0000,Equity,507504,225949.0500,100.0000,4073802,0.0000,-281555,-281555,0.0000,0.0000,0.0000
21,LIFE SETTLEMENT ASSETS ORD,LSAA LN,Fully Paid,3099584,1.4600,4525392,4525392,USD,1.0000,Equity,4525392,4525392.6400,100.0000,LSAA LN,Fully Paid,4518981,1.4600,225949,225949,USD,1.0000,Equity,225949,4525392.6400,100.0000,-1419397,0.0000,4299443,4299443,0.0000,0.0000,0.0000
22,MYANMAR INVESTMENTS INT ORD,MIL LN,Fully Paid,3252693,0.0750,243951,243951,USD,1.0000,Equity,243951,243951.9750,100.0000,MIL LN,Fully Paid,3099584,0.0750,4525392,4525392,USD,1.0000,Equity,4525392,243951.9750,100.0000,153109,0.0000,-4281441,-4281441,0.0000,0.0000,0.0000
23,RIVERSTONE CREDIT OPPS INC ORD,RCOI LN,Fully Paid,5738583,0.9325,5351228,5351228,USD,1.0000,Equity,5351228,5351228.6475,100.0000,RCOI LN,Fully Paid,3252693,0.9325,243951,243951,USD,1.0000,Equity,243951,5351228.6475,100.0000,2485890,0.0000,5107277,5107277,0.0000,0.0000,0.0000
24,RIVERSTONE ENERGY ORD,RSE LN,Fully Paid,838314,5.9400,4979585,4979585,GBP,1.2352,Equity,7597447,7597447.8899,100.0000,RSE LN,Fully Paid,5738583,6.1000,5351228,5351228,GBP,1.2320,Equity,5351228,7761719.9633,100.0000,-4900269,-0.1600,-371643,-371643,0.0032,-164272.0734,0.0000
25,British Pound Forward Cash,GBP.F,Cash,-12500000,1.0000,-12500000,-12500000,GBP,1.2352,FFX,-19071488,667502.0800,3.5000,GBP.F,Cash,6664284,1.0000,5584669,5584669,GBP,1.2320,FFX,8520637,664048.0000,3.5000,-19164284,0.0000,-18084669,-18084669,0.0032,3454.0800,0.0000
26,Euro Forward Cash,EUR.F,Cash,-17500000,1.0000,-17500000,-17500000,EUR,1.0851,FFX,-20605235,721183.2311,3.5000,EUR.F,Cash,-12500000,1.0000,-12500000,-12500000,EUR,1.0863,FFX,-19071488,722779.2101,3.5000,-5000000,0.0000,-5000000,-5000000,-0.0012,-1595.9790,0.0000
27,United States Dollar Forward Cash,USD.F,Cash,31597693,1.0000,31597693,31597693,USD,1.0000,FFX,31597693,315976.9350,1.0000,USD.F,Cash,-17500000,1.0000,-17500000,-17500000,USD,1.0000,FFX,-20605235,315976.9350,1.0000,49097693,0.0000,49097693,49097693,0.0000,0.0000,0.0000
28,ISHARES NASDAQ BIOTECHNOLOGY,IBB,Cash,-7800,134.8000,-1051440,-1051440,USD,1.0000,Fund,-1051440,157716.0000,15.0000,IBB,Cash,31597693,136.5500,31597693,31597693,USD,1.0000,Fund,31597693,159763.5000,15.0000,-31605493,-1.7500,-32649133,-32649133,0.0000,-2047.5000,0.0000
29,Baring Vostok,BARVTCO,Fully Paid,1509000,0.0000,0,0,USD,1.0000,Fund,0,0.0000,0.0000,BARVTCO,Fully Paid,1509000,0.0000,0,0,USD,1.0000,Fund,0,0.0000,0.0000,0,0.0000,0,0,0.0000,0.0000,0.0000
30,E-Mini Russ 2000 Mar23,RTYH3 Index,Cash,-92,1899.1000,-250160,-8735859,USD,1.0000,Future,-8735860,1090795.3348,12.4864,RTYH3 Index,Cash,1236299,1934.5000,19854961,19854961,USD,1.0000,Future,323413,1111128.2055,12.4864,-1236391,-35.4000,-20105121,-28590820,0.0000,-20332.8708,0.0000
31,EURO STOXX 50 Mar23,VGH3 Index,Cash,-13,4157.0000,-25284,-540410,EUR,1.0851,Future,-636301,86463.2599,13.5884,VGH3 Index,Cash,-92,4181.0000,-250160,-8735859,EUR,1.0863,Future,-8735860,87154.8944,13.5884,79,-24.0000,224876,8195449,-0.0012,-691.6344,0.0000
32,FTSE CHINA A50 Feb23,XUG3 Index,Cash,-175,14099.0000,17325,-2467325,USD,1.0000,Future,-2467325,360339.5538,14.6045,XUG3 Index,Cash,-13,13971.0000,-25284,-540410,USD,1.0000,Future,-636301,357068.1542,14.6045,-162,128.0000,42609,-1926915,0.0000,3271.3996,0.0000
33,NASDAQ 100 E-MINI Mar23,NQH3 Index,Cash,-8,11992.5000,-5336,-1918800,USD,1.0000,Future,-1918800,202074.3615,10.5313,NQH3 Index,Cash,-175,12091.0000,17325,-2467325,USD,1.0000,Future,-2467325,203734.0925,10.5313,167,-98.5000,-22661,548525,0.0000,-1659.7310,0.0000
34,S&P500 EMINI FUT Mar23,ESH3 Index,Cash,-45,4041.0000,31837,-9092250,USD,1.0000,Future,-9092250,1046492.1525,11.5097,ESH3 Index,Cash,-8,4077.2500,-5336,-1918800,USD,1.0000,Future,-1918800,1055879.7646,11.5097,-37,-36.2500,37173,-7173450,0.0000,-9387.6121,0.0000
35,Australian Dollars,AUD,Cash,-1651972,1.0000,-1651972,-1651972,AUD,0.7060,Spot,-1166292,0.0000,0.0000,AUD,Cash,-45,1.0000,31837,-9092250,AUD,0.7055,Spot,-9092250,0.0000,0.0000,-1651927,0.0000,-1683809,7440278,0.0005,0.0000,0.0000
36,British Pounds,GBP,Cash,4191040,1.0000,4191040,4191040,GBP,1.2352,Spot,5176773,0.0000,0.0000,GBP,Cash,4191040,1.0000,4191040,4191040,GBP,1.2320,Spot,5176773,0.0000,0.0000,0,0.0000,0,0,0.0032,0.0000,0.0000
37,United States Dollars,USD,Cash,2947793,1.0000,2947793,2947793,USD,1.0000,Spot,2947793,0.0000,0.0000,USD,Cash,2947793,1.0000,2947793,2947793,USD,1.0000,Spot,2947793,0.0000,0.0000,0,0.0000,0,0,0.0000,0.0000,0.0000

In [9]:
#Dropping columns that aren't relevant
merged_df = merged_df.drop('Code_y', axis=1)
merged_df = merged_df.drop('Position Type_y', axis=1)
merged_df = merged_df.drop('Price Ccy_y', axis=1)
merged_df = merged_df.drop('Instrument Class_y', axis=1)
merged_df.head()

,Instrument,Code_x,Position Type_x,Quantity_x,Unit Price\n(Local)\n_x,Value \n(Local)_x,Exposure \n(Local)_x,Price Ccy_x,FX Rate_x,Instrument Class_x,Exposure \n(USD)_x,Requirement \n(USD)_x,%Req_x,Quantity_y,Unit Price\n(Local)\n_y,Value \n(Local)_y,Exposure \n(Local)_y,FX Rate_y,Exposure \n(USD)_y,Requirement \n(USD)_y,%Req_y,Quantity change,Price Change,Local Value Change,Local Exposure Change,USD Value Change,Requirement Change,%Req Change
0,CT PPTY TR ORD,CTPT LN,Cash,2556887,0.7300,1866527,1866527,GBP,1.2352,Equity,2847796,2242554.4718,78.7470,2556887,0.7100,1866527,1866527,1.2320,2847796,2169284.1367,78.7273,0,0.0200,0,0,0.0032,73270.3352,0.0197
1,FERGUSON ORD,FERG LN,Cash,1157,113.4500,131261,131261,GBP,1.2352,Equity,200268,43330.1308,21.6360,1157,113.6000,131261,131261,1.2320,200268,43020.3799,21.5646,0,-0.1500,0,0,0.0032,309.7510,0.0714
2,HARBOURVEST GLOBAL ORD,HVPE LN,Cash,131249,22.1000,2900602,2900602,GBP,1.2352,Equity,4425505,1449908.6601,32.7626,131249,22.1000,2900602,2900602,1.2320,4425505,1411042.0708,32.0502,0,0.0000,0,0,0.0032,38866.5892,0.7124
3,MAGELLAN GLOBAL UNT,MGF AU,Cash,500000,1.3950,697500,697500,AUD,0.7060,Equity,347659,75219.6294,21.6360,500000,1.3900,697500,697500,0.7055,347659,74596.7618,21.5646,0,0.0050,0,0,0.0005,622.8675,0.0714
4,NB GLOBAL MONTHLY INCOME FUND ORD,NBMI LN,Cash,3000000,0.7460,2238000,2238000,GBP,1.2352,Equity,3414559,2855789.4108,83.6357,3000000,0.7320,2238000,2238000,1.2320,3414559,2887549.2833,86.6315,0,0.0140,0,0,0.0032,-31759.8725,-2.9958

In [10]:
#Renaming the columns to make it easier to understand
merged_df.rename(columns={'Code_x': 'Code', 'Position Type_x': 'Position Type', 'Quantity_x': 'Quantity (Day 1)', 'Unit Price\n(Local)\n_x': 'Unit Price in GDP (Day 1)','Value \n(Local)_x': 'Value in GDP (Day 1)', 'Exposure \n(Local)_x': 'Exposure in GDP (Day 1)','Price Ccy_x': 'Price Ccy', 'FX Rate_x': 'FX Rate (Day 1)','Instrument Class_x': 'Instrument Class', 'Exposure \n(USD)_x': 'Exposure in USD (Day 1)','Requirement \n(USD)_x': 'Requirement in USD (Day 1)', '%Req_x': '%Req (Day 1)'}, inplace=True)
merged_df.rename(columns={'Quantity_y': 'Quantity (Day 2)', 'Unit Price\n(Local)\n_y': 'Unit Price in GDP (Day 2)','Value \n(Local)_y': 'Value in GDP (Day 2)', 'Exposure \n(Local)_y': 'Exposure in GDP (Day 2)','FX Rate_y': 'FX Rate (Day 2)','Exposure \n(USD)_y': 'Exposure in USD (Day 2)','Requirement \n(USD)_y': 'Requirement in USD (Day 2)', '%Req_y': '%Req (Day 2)'}, inplace=True)
merged_df.head()

,Instrument,Code,Position Type,Quantity (Day 1),Unit Price in GDP (Day 1),Value in GDP (Day 1),Exposure in GDP (Day 1),Price Ccy,FX Rate (Day 1),Instrument Class,Exposure in USD (Day 1),Requirement in USD (Day 1),%Req (Day 1),Quantity (Day 2),Unit Price in GDP (Day 2),Value in GDP (Day 2),Exposure in GDP (Day 2),FX Rate (Day 2),Exposure in USD (Day 2),Requirement in USD (Day 2),%Req (Day 2),Quantity change,Price Change,Local Value Change,Local Exposure Change,USD Value Change,Requirement Change,%Req Change
0,CT PPTY TR ORD,CTPT LN,Cash,2556887,0.7300,1866527,1866527,GBP,1.2352,Equity,2847796,2242554.4718,78.7470,2556887,0.7100,1866527,1866527,1.2320,2847796,2169284.1367,78.7273,0,0.0200,0,0,0.0032,73270.3352,0.0197
1,FERGUSON ORD,FERG LN,Cash,1157,113.4500,131261,131261,GBP,1.2352,Equity,200268,43330.1308,21.6360,1157,113.6000,131261,131261,1.2320,200268,43020.3799,21.5646,0,-0.1500,0,0,0.0032,309.7510,0.0714
2,HARBOURVEST GLOBAL ORD,HVPE LN,Cash,131249,22.1000,2900602,2900602,GBP,1.2352,Equity,4425505,1449908.6601,32.7626,131249,22.1000,2900602,2900602,1.2320,4425505,1411042.0708,32.0502,0,0.0000,0,0,0.0032,38866.5892,0.7124
3,MAGELLAN GLOBAL UNT,MGF AU,Cash,500000,1.3950,697500,697500,AUD,0.7060,Equity,347659,75219.6294,21.6360,500000,1.3900,697500,697500,0.7055,347659,74596.7618,21.5646,0,0.0050,0,0,0.0005,622.8675,0.0714
4,NB GLOBAL MONTHLY INCOME FUND ORD,NBMI LN,Cash,3000000,0.7460,2238000,2238000,GBP,1.2352,Equity,3414559,2855789.4108,83.6357,3000000,0.7320,2238000,2238000,1.2320,3414559,2887549.2833,86.6315,0,0.0140,0,0,0.0032,-31759.8725,-2.9958

In [12]:
merged_df = merged_df.loc[:,['Instrument','Instrument Class', 'Code', 'Price Ccy', 'Position Type', 'Quantity (Day 1)', 'Quantity (Day 2)', 'Quantity change', 'Unit Price in GDP (Day 1)', 'Unit Price in GDP (Day 2)', 'Price Change', 'Value in GDP (Day 1)', 'Value in GDP (Day 2)', 'Local Value Change', 'Exposure in GDP (Day 1)', 'Exposure in GDP (Day 2)', 'Local Exposure Change', 'Exposure in USD (Day 1)', 'Exposure in USD (Day 2)', 'USD Value Change', 'Requirement in USD (Day 1)','Requirement in USD (Day 2)','Requirement Change', '%Req (Day 1)','%Req (Day 2)', '%Req Change']]

In [13]:
merged_df.head()

,Instrument,Instrument Class,Code,Price Ccy,Position Type,Quantity (Day 1),Quantity (Day 2),Quantity change,Unit Price in GDP (Day 1),Unit Price in GDP (Day 2),Price Change,Value in GDP (Day 1),Value in GDP (Day 2),Local Value Change,Exposure in GDP (Day 1),Exposure in GDP (Day 2),Local Exposure Change,Exposure in USD (Day 1),Exposure in USD (Day 2),USD Value Change,Requirement in USD (Day 1),Requirement in USD (Day 2),Requirement Change,%Req (Day 1),%Req (Day 2),%Req Change
0,CT PPTY TR ORD,Equity,CTPT LN,GBP,Cash,2556887,2556887,0,0.7300,0.7100,0.0200,1866527,1866527,0,1866527,1866527,0,2847796,2847796,0.0032,2242554.4718,2169284.1367,73270.3352,78.7470,78.7273,0.0197
1,FERGUSON ORD,Equity,FERG LN,GBP,Cash,1157,1157,0,113.4500,113.6000,-0.1500,131261,131261,0,131261,131261,0,200268,200268,0.0032,43330.1308,43020.3799,309.7510,21.6360,21.5646,0.0714
2,HARBOURVEST GLOBAL ORD,Equity,HVPE LN,GBP,Cash,131249,131249,0,22.1000,22.1000,0.0000,2900602,2900602,0,2900602,2900602,0,4425505,4425505,0.0032,1449908.6601,1411042.0708,38866.5892,32.7626,32.0502,0.7124
3,MAGELLAN GLOBAL UNT,Equity,MGF AU,AUD,Cash,500000,500000,0,1.3950,1.3900,0.0050,697500,697500,0,697500,697500,0,347659,347659,0.0005,75219.6294,74596.7618,622.8675,21.6360,21.5646,0.0714
4,NB GLOBAL MONTHLY INCOME FUND ORD,Equity,NBMI LN,GBP,Cash,3000000,3000000,0,0.7460,0.7320,0.0140,2238000,2238000,0,2238000,2238000,0,3414559,3414559,0.0032,2855789.4108,2887549.2833,-31759.8725,83.6357,86.6315,-2.9958

In [14]:
merged_df.sort_values(by=['Instrument Class', 'Price Ccy', 'Position Type'])

,Instrument,Instrument Class,Code,Price Ccy,Position Type,Quantity (Day 1),Quantity (Day 2),Quantity change,Unit Price in GDP (Day 1),Unit Price in GDP (Day 2),Price Change,Value in GDP (Day 1),Value in GDP (Day 2),Local Value Change,Exposure in GDP (Day 1),Exposure in GDP (Day 2),Local Exposure Change,Exposure in USD (Day 1),Exposure in USD (Day 2),USD Value Change,Requirement in USD (Day 1),Requirement in USD (Day 2),Requirement Change,%Req (Day 1),%Req (Day 2),%Req Change
3,MAGELLAN GLOBAL UNT,Equity,MGF AU,AUD,Cash,500000,500000,0,1.3950,1.3900,0.0050,697500,697500,0,697500,697500,0,347659,347659,0.0005,75219.6294,74596.7618,622.8675,21.6360,21.5646,0.0714
5,NEW ENERGY SOLAR STAPLED UNT,Equity,NEW AU,AUD,Cash,7684727,7684727,0,0.2000,0.0680,0.1320,1536945,1536945,0,1536945,1536945,0,766068,766068,0.0005,656356.2520,222741.5845,433614.6675,85.6785,85.6387,0.0398
10,UMG ORD,Equity,UMG NA,EUR,Synthetic,-44000,-44000,0,23.6350,23.4700,0.1650,-49500,-49500,0,-1039940,-1039940,0,-1224469,-1224469,-0.0012,183670.3566,182791.7473,878.6093,15.0000,15.0000,0.0000
0,CT PPTY TR ORD,Equity,CTPT LN,GBP,Cash,2556887,2556887,0,0.7300,0.7100,0.0200,1866527,1866527,0,1866527,1866527,0,2847796,2847796,0.0032,2242554.4718,2169284.1367,73270.3352,78.7470,78.7273,0.0197
1,FERGUSON ORD,Equity,FERG LN,GBP,Cash,1157,1157,0,113.4500,113.6000,-0.1500,131261,131261,0,131261,131261,0,200268,200268,0.0032,43330.1308,43020.3799,309.7510,21.6360,21.5646,0.0714
2,HARBOURVEST GLOBAL ORD,Equity,HVPE LN,GBP,Cash,131249,131249,0,22.1000,22.1000,0.0000,2900602,2900602,0,2900602,2900602,0,4425505,4425505,0.0032,1449908.6601,1411042.0708,38866.5892,32.7626,32.0502,0.7124
4,NB GLOBAL MONTHLY INCOME FUND ORD,Equity,NBMI LN,GBP,Cash,3000000,3000000,0,0.7460,0.7320,0.0140,2238000,2238000,0,2238000,2238000,0,3414559,3414559,0.0032,2855789.4108,2887549.2833,-31759.8725,83.6357,86.6315,-2.9958
6,PANTHEON INTERNATIONAL CF,Equity,PIN LN,GBP,Cash,1421921,1421921,0,2.6450,2.6450,0.0000,3760981,3760981,0,3760981,3760981,0,5738200,5738200,0.0032,2809681.7488,2705224.2858,104457.4631,48.9645,47.3893,1.5752
9,TRIAN INVESTORS 1 ORD,Equity,TI1 LN,GBP,Cash,1333000,1333000,0,1.8400,1.8450,-0.0050,2452720,2452720,0,2452720,2452720,0,3742161,3742161,0.0032,3706764.6515,3710261.6271,-3496.9756,99.0541,99.3932,-0.3391
11,VPC SPECIALTY LENDING INVESTS ORD,Equity,VSL LN,GBP,Cash,1070295,838314,231981,0.8380,0.8340,0.0040,896907,4979585,-4082678,896907,4979585,-4082678,1368428,7597447,0.0032,907793.9185,8436085.3051,-7528291.3867,66.3384,100.0000,-33.6616
12,VPC SPECIALTY LENDING INVESTS ORD,Equity,VSL LN,GBP,Fully Paid,6664284,838314,5825970,0.8380,0.8340,0.0040,5584669,4979585,605084,5584669,4979585,605084,8520637,7597447,0.0032,8520637.3389,8436085.3051,84552.0338,100.0000,100.0000,0.0000
14,ALLIED MINDS ORD,Equity,ALM LN,GBP,Fully Paid,18462237,2760062,15702175,0.1385,0.1385,0.0000,2557019,1490433,1066586,2557019,1490433,1066586,3901293,1490433,0.0032,3901293.8319,3881106.0581,20187.7738,100.0000,100.0000,0.0000
15,AMEDEO AIR FOUR PLUS ORD,Equity,AA4 LN,GBP,Fully Paid,23788430,18462237,5326193,0.4000,0.4000,0.0000,9515372,2557019,6958353,9515372,2557019,6958353,14517784,3901293,0.0032,14517784.2331,14442659.9905,75124.2426,100.0000,100.0000,0.0000
17,DORIC NIMROD AIR TWO LTD,Equity,DNA2 LN,GBP,Fully Paid,4242783,8000000,-3757217,1.0350,1.0400,-0.0050,4391280,1120000,3271280,4391280,1120000,3271280,6699860,1120000,0.0032,6699860.1239,6697389.7788,2470.3451,100.0000,100.0000,0.0000
24,RIVERSTONE ENERGY ORD,Equity,RSE LN,GBP,Fully Paid,838314,5738583,-4900269,5.9400,6.1000,-0.1600,4979585,5351228,-371643,4979585,5351228,-371643,7597447,5351228,0.0032,7597447.8899,7761719.9633,-164272.0734,100.0000,100.0000,0.0000
18,ENERGYO SOLUTIONS INVEST ORD,Equity,EOS SF,SEK,Fully Paid,909529,4242783,-3333254,0.0000,0.0000,0.0000,0,4391280,-4391280,0,4391280,-4391280,0,6699860,0.0006,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
7,RESTAURANT BRANDS INTERN,Equity,QSR,USD,Cash,-8500,-8500,0,66.5900,66.9300,-0.3400,-566015,-566015,0,-566015,-566015,0,-566015,-566015,0.0000,84902.2500,85335.7500,-433.5000,15.0000,15.0000,0.0000
8,THIRD POINT INVESTORS ORD,Equity,TPOU LN,USD,Cash,119714,119714,0,20.4000,20.4000,0.0000,2442165,2442165,0,2442165,2442165,0,2442165,2442165,0.0000,1704081.4860,1751012.4531,-46930.9671,69.7775,71.6992,-1.9217
13,AFRICA OPPORTUNITY ORD,Equity,AOF LN,USD,Fully Paid,2760062,1070295,1689767,0.5400,0.5400,0.0000,1490433,896907,593526,1490433,896907,593526,1490433,1368428,0.0000,1490433.4800,1490433.4800,0.0000,100.0000,100.0000,0.0000
16,ASEANA PROPERTIES ORD,Equity,ASPL LN,USD,Fully Paid,8000000,23788430,-15788430,0.1400,0.1400,0.0000,1120000,9515372,-8395372,1120000,9515372,-8395372,1120000,14517784,0.0000,1120000.0000,1120000.0000,0.0000,100.0000,100.0000,0.0000
19,JPEL PRIVATE EQUITY ORD,Equity,JPEL LN,USD,Fully Paid,445179,909529,-464350,1.1400,1.1400,0.0000,507504,0,507504,507504,0,507504,507504,0,0.0000,507504.0600,507504.0600,0.0000,100.0000,100.0000,0.0000
20,KUBERA CROSS-BORDER FUND,Equity,KUBC LN,USD,Fully Paid,4518981,445179,4073802,0.0500,0.0500,0.0000,225949,507504,-281555,225949,507504,-281555,225949,507504,0.0000,225949.0500,225949.0500,0.0000,100.0000,100.0000,0.0000
21,LIFE SETTLEMENT ASSETS ORD,Equity,LSAA LN,USD,Fully Paid,3099584,4518981,-1419397,1.4600,1.4600,0.0000,4525392,225949,4299443,4525392,225949,4299443,4525392,225949,0.0000,4525392.6400,4525392.6400,0.0000,100.0000,100.0000,0.0000
22,MYANMAR INVESTMENTS INT ORD,Equity,MIL LN,USD,Fully Paid,3252693,3099584,153109,0.0750,0.0750,0.0000,243951,4525392,-4281441,243951,4525392,-4281441,243951,4525392,0.0000,243951.9750,243951.9750,0.0000,100.0000,100.0000,0.0000
23,RIVERSTONE CREDIT OPPS INC ORD,Equity,RCOI LN,USD,Fully Paid,5738583,3252693,2485890,0.9325,0.9325,0.0000,5351228,243951,5107277,5351228,243951,5107277,5351228,243951,0.0000,5351228.6475,5351228.6475,0.0000,100.0000,100.0000,0.0000
26,Euro Forward Cash,FFX,EUR.F,EUR,Cash,-17500000,-12500000,-5000000,1.0000,1.0000,0.0000,-17500000,-12500000,-5000000,-17500000,-12500000,-5000000,-20605235,-19071488,-0.0012,721183.2311,722779.2101,-1595.9790,3.5000,3.5000,0.0000
25,British Pound Forward Cash,FFX,GBP.F,GBP,Cash,-12500000,6664284,-19164284,1.0000,1.0000,0.0000,-12500000,5584669,-18084669,-12500000,5584669,-18084669,-19071488,8520637,0.0032,667502.0800,664048.0000,3454.0800,3.5000,3.5000,0.0000
27,United States Dollar Forward Cash,FFX,USD.F,USD,Cash,31597693,-17500000,49097693,1.0000,1.0000,0.0000,31597693,-17500000,49097693,31597693,-17500000,49097693,31597693,-20605235,0.0000,315976.9350,315976.9350,0.0000,1.0000,1.0000,0.0000
28,ISHARES NASDAQ BIOTECHNOLOGY,Fund,IBB,USD,Cash,-7800,31597693,-31605493,134.8000,136.5500,-1.7500,-1051440,31597693,-32649133,-1051440,31597693,-32649133,-1051440,31597693,0.0000,157716.0000,159763.5000,-2047.5000,15.0000,15.0000,0.0000
29,Baring Vostok,Fund,BARVTCO,USD,Fully Paid,1509000,1509000,0,0.0000,0.0000,0.0000,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
31,EURO STOXX 50 Mar23,Future,VGH3 Index,EUR,Cash,-13,-92,79,4157.0000,4181.0000,-24.0000,-25284,-250160,224876,-540410,-8735859,8195449,-636301,-8735860,-0.0012,86463.2599,87154.8944,-691.6344,13.5884,13.5884,0.0000
30,E-Mini Russ 2000 Mar23,Future,RTYH3 Index,USD,Cash,-92,1236299,-1236391,1899.1000,1934.5000,-35.4000,-250160,19854961,-20105121,-8735859,19854961,-28590820,-8735860,323413,0.0000,1090795.3348,1111128.2055,-20332.8708,12.4864,12.4864,0.0000
32,FTSE CHINA A50 Feb23,Future,XUG3 Index,USD,Cash,-175,-13,-162,14099.0000,13971.0000,128.0000,17325,-25284,42609,-2467325,-540410,-1926915,-2467325,-636301,0.0000,360339.5538,357068.1542,3271.3996,14.6045,14.6045,0.0000
33,NASDAQ 100 E-MINI Mar23,Future,NQH3 Index,USD,Cash,-8,-175,167,11992.5000,12091.0000,-98.5000,-5336,17325,-22661,-1918800,-2467325,548525,-1918800,-2467325,0.0000,202074.3615,203734.0925,-1659.7310,10.5313,10.5313,0.0000
34,S&P500 EMINI FUT Mar23,Future,ESH3 Index,USD,Cash,-45,-8,-37,4041.0000,4077.2500,-36.2500,31837,-5336,37173,-9092250,-1918800,-7173450,-9092250,-1918800,0.0000,1046492.1525,1055879.7646,-9387.6121,11.5097,11.5097,0.0000
35,Australian Dollars,Spot,AUD,AUD,Cash,-1651972,-45,-1651927,1.0000,1.0000,0.0000,-1651972,31837,-1683809,-1651972,-9092250,7440278,-1166292,-9092250,0.0005,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
36,British Pounds,Spot,GBP,GBP,Cash,4191040,4191040,0,1.0000,1.0000,0.0000,4191040,4191040,0,4191040,4191040,0,5176773,5176773,0.0032,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
37,United States Dollars,Spot,USD,USD,Cash,2947793,2947793,0,1.0000,1.0000,0.0000,2947793,2947793,0,2947793,2947793,0,2947793,2947793,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000